name: Release Uai Icons
on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: icons-release
  cancel-in-progress: true

jobs:
  release:
    name: Release icons
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - name: Install npm dependencies
        run: npm i

      - name: Build
        env:
          FIGMA: ${{ vars.FIGMA }}
        run: |
          echo "${FIGMA}" | tr ';' '\n' > .env
          npm run build

      - name: Create Empty Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "ti@dito.com.br"
          git config --global user.name "Dito bot"
          git commit --allow-empty -m "Feat: release new icons"   
          git push origin main

         
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release
