name: Release Uai Icons
on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: icons-release
  cancel-in-progress: true

jobs:
  release:
    name: Release icons
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'dito@users.noreply.github.com'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - name: Install npm dependencies
        run: npm i

      - name: Release
        env:
          FIGMA: ${{ vars.FIGMA }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "${FIGMA}" | tr ';' '\n' > .env
          npm run build
          git commit --allow-empty -m "ci(icons): release new version"
          git push
          npx semantic-release
